apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pipelinev2
description: pipeline for ejer2
serialPipeline:
  stages:
  - targetId: dev
    profiles: 
      - dev
  - targetId: staging
    profiles:
      - staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev cluster for deploys
gke:
  cluster: projects/igneous-mason-347617/locations/us-central1-c/clusters/cluster-devops
---  
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster for deploys
gke:
  cluster: projects/igneous-mason-347617/locations/us-central1-c/clusters/cluster-devops  